- name: install apt packages for the bhive
  apt:
    name:
    - python3-rpi.gpio
    state: present

- name: link bhive systemd service
  file:
    state: link
    src: /home/pi/bhive/systemd/bhive.service
    dest: /etc/systemd/system/bhive.service

- name: enable bhive systemd service
  systemd:
    state: started
    enabled: yes
    name: bhive

- name: active w1-gpio service
  lineinfile:
    path: /boot/config.txt
    line: dtoverlay=w1-gpio,gpiopin=11

- name: load kernel modules
  file:
    state: present
    path: /etc/modprobe.d/w1-gpio.conf
    content: |
      wire
      w1-gpio
      w1-therm