name: Go test, build and prerelase

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

#    - name: Test
#      run: go test -v ./...
#      working-directory: ./packages/buffer
      
    - name: Build bHive client
      run: env GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="-s -w" -v
      working-directory: ./bhive

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "staging"
        prerelease: false
        title: "Development Build"
        files: |
          bhive/bhive
